# Generated by Django 5.1.3 on 2024-11-19 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_of_count_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CountPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_of_count_point', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('count_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countpod.countlocation')),
            ],
        ),
    ]
